### ISSUE TITLE
Cannot be found: PieChart, DoughnutChart and PolarAreaChart 

### ISSUE THREAD

**Issue by SonicTTH** [martinobordin/Chart.Mvc#28]
Hello,

When I have a view and I add these Lines:

@using Chart.Mvc.ComplexChart;
@using Chart.Mvc.Extensions;

I can instanciate BarChart, LineChart and RadarChart but not these: PieChart, DoughnutChart and PolarAreaChart. 

What am I missing?

Great wrapper so far!

**Comment by martinobordin** [comment]
Can't you see that classes in the namespace? Did you check the sample
solution in github?

Il 15 ott 2016 5:20 PM, "SonicTTH" notifications@github.com ha scritto:

Hello,

When I have a view and I add these Lines:

@using https://github.com/using Chart.Mvc.ComplexChart;
@using https://github.com/using Chart.Mvc.Extensions;

I can instanciate BarChart, LineChart and RadarChart but not these:
PieChart, DoughnutChart and PolarAreaChart.

What am I missing?

Great wrapper so far!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/martinobordin/Chart.Mvc/issues/28, or mute the thread

**Comment by SonicTTH** [comment]
Yes I cant see the classes and the webpage cannot be compiled or executed since the compiler cant find the classes as well.

Im using Chart.Mvc through an installed nuget-package.

I also tried out downloading the code and adding the project to my solution, referencing it in the references of my webproject. They still cant be seen.

I was even able to replicate that same problem on another computer.

**Comment by martinobordin** [comment]
If You look The assembly with the object browser can you see the classes?

I just used this package last week and it is working since years

Inviato da iPhone

**Comment by SonicTTH** [comment]
Ah, never used that tool before. Okay theyre under SimpleChart. And if visual studio would have been able to resolve these classnames then I wouldnt even have come to ask. But somehow it wasnt able.

Thanks for that hint though. Actually learned something useful by that!

**Comment by martinobordin** [comment]
Great ☺️

Inviato da iPhone
