### ISSUE TITLE
BarChart stacked

### ISSUE THREAD

**Issue by cooxkie** [martinobordin/Chart.Mvc#38]
Hi, 

I haven't found any options in order to configure stacked BarChart (http://www.chartjs.org/docs/#bar-chart)
Do you have any solution ?

Regards,

Eric

**Comment by martinobordin** [comment]
It's not supported in chart.mvc, because it's using chart.js v1

Il 06 dic 2016 3:07 PM, "Cooxkie" <notifications@github.com> ha scritto:

**Comment by cooxkie** [comment]
ok, too bad ...

Do you plan to support higher chart.js version ?

Regards,

Eric

**Comment by martinobordin** [comment]
​Some functionalities are in the repository..but there are some​ problems
because they used different types for a single "property".. Sometimes a
property is string, sometimes is an array..and that's not possible in c#

*Martino Bordin*
*IT Consultant - Software Architect*

*mobile:* +39 348 0136512
*skype:* martino.bordin
*mail:* info@martinobordin.it
*web:* www.martinobordin.it

**Comment by cooxkie** [comment]
I understand ... thanks for your effort. Your library is really cool even if only chart.js v1 is supported ;-)

**Comment by martinobordin** [comment]
Yes, thank you :)

Il 06 dic 2016 4:27 PM, "Cooxkie" <notifications@github.com> ha scritto:
